- name: Initialize Kubernetes master node
  hosts: master-nodes
  become: true
  tasks:
    - name: Initialize Kubernetes master node
      ansible.builtin.command:
        chdir: /root
        cmd: |-
          kubeadm init
        creates: /etc/kubernetes/admin.conf
    - name: Create .kube directory
      ansible.builtin.file:
        path: /root/.kube
        state: directory
        mode: '0755'
    - name: Copy Kubernetes configuration file
      ansible.builtin.command:
        cmd: "cp -i /etc/kubernetes/admin.conf ~/.kube/config"
        creates: /root/.kube/config
    - name: Export KUBECONFIG environment variable
      ansible.builtin.lineinfile:
        path: /root/.bashrc
        line: "export KUBECONFIG=/root/.kube/config"
        state: present
      changed_when: true
    - name: Set up change namespace alias
      ansible.builtin.lineinfile:
        path: /root/.bashrc
        line: "alias kns='kubectl config set-context --current --namespace '"
        state: present

- name: Join worker nodes to the Kubernetes cluster
  hosts: worker-nodes
  become: true
  tasks:
    - name: Fetch join command from master
      ansible.builtin.command: kubeadm token create --print-join-command
      delegate_to: "{{ groups['master-nodes'][0] }}"
      register: join_command
      changed_when: false
    - name: Join worker nodes to the Kubernetes cluster
      ansible.builtin.command:
        cmd: "{{ join_command.stdout_lines[0] }}"
        creates: /root/kubeadm-join.log
- name: Install Calico network plugin
  hosts: master-nodes
  become: true
  tasks:
    - name: Make sure the cluster have install Calico CNI
      kubernetes.core.k8s:
        state: present
        src: "https://raw.githubusercontent.com/projectcalico/calico/v3.26.1/manifests/calico.yaml"
