- name: Install init resources (monitoring, logging, Nginx Ingress Controller)
  hosts: master-nodes
  become: true
  tasks:
    - name: Add Prometheus repository
      kubernetes.core.helm_repository:
        name: prometheus-community
        repo_url: https://prometheus-community.github.io/helm-charts
        state: present
    - name: Install Prometheus stack through helm
      kubernetes.core.helm:
        atomic: false
        name: kube-prometheus-stack
        namespace: monitoring
        chart_version: 62.3.1
        update_repo_cache: true
        create_namespace: true
        chart_ref: prometheus-community/kube-prometheus-stack
        release_state: present
        wait: false
    - name: Add Nginx repository
      kubernetes.core.helm_repository:
        name: bitnami
        repo_url: https://charts.bitnami.com/bitnami
        state: present
    - name: Install Ingress Ingress Controller
      kubernetes.core.helm:
        values:
          serviceMonitor:
            enable: true
            namespace: monitoring
          service:
            type: NodePort
            nodePorts:
              http: 30080
              https: 30443
        atomic: false
        name: nginx-ingress
        namespace: nginx-ingress
        chart_version: 18.2.6
        update_repo_cache: true
        create_namespace: true
        chart_ref: bitnami/nginx
        release_state: present
        wait: false
