- name: Install init resources (monitoring, logging, Nginx Ingress Controller)
  hosts: master-nodes
  become: true
  tasks:
    - name: Add Prometheus repository
      kubernetes.core.helm_repository:
        name: prometheus-community
        repo_url: https://prometheus-community.github.io/helm-charts
        state: present
    - name: Install Prometheus stack through helm
      kubernetes.core.helm:
        atomic: false
        name: kube-prometheus-stack
        namespace: monitoring
        chart_version: 62.3.1
        update_repo_cache: true
        create_namespace: true
        chart_ref: prometheus-community/kube-prometheus-stack
        release_state: present
        wait: false
    - name: Add Nginx repository
      kubernetes.core.helm_repository:
        name: ingress-nginx
        repo_url: https://kubernetes.github.io/ingress-nginx
        state: present
    - name: Install Ingress Ingress Controller
      kubernetes.core.helm:
        values:
          controller:
           kind: DaemonSet
           service:
             type: NodePort
             nodePorts:
               http: 30080
               https: 30443
        atomic: false
        name: nginx-ingress
        namespace: ingress-nginx
        chart_version: 4.11.3
        update_repo_cache: true
        create_namespace: true
        chart_ref: ingress-nginx/ingress-nginx
        release_state: present
        wait: false
